/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio5;

import Menu.Menu;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author conej
 */
public class Carreras extends javax.swing.JFrame {
    HiloCarro1 hilo1;
    HiloCarro1 hilo2;
    HiloCarro1 hilo3;
    public Carreras() {
        initComponents();
        this.setLocationRelativeTo(null);
        hilo1= new HiloCarro1(carrito1,lbl_barrera);
    }
    /*    public JLabel getlbl1(){
    return carrito1;
    }*/
    public JLabel getlbl2(){
        return carrito2;
    }
    public JLabel getlbl3(){
        return carrito3;
    }
    public JLabel getlbl_barrera(){
        return lbl_barrera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        miboton5 = new componentes.Miboton();
        jButton1 = new javax.swing.JButton();
        btiniciar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        carrito1 = new javax.swing.JLabel();
        carrito2 = new javax.swing.JLabel();
        carrito3 = new javax.swing.JLabel();
        lbl_barrera = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(678, 425));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miboton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/atras.png"))); // NOI18N
        miboton5.setContentAreaFilled(false);
        miboton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/atras2.png"))); // NOI18N
        miboton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miboton5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miboton5MouseReleased(evt);
            }
        });
        miboton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miboton5ActionPerformed(evt);
            }
        });
        miboton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                miboton5KeyPressed(evt);
            }
        });
        jPanel1.add(miboton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 80, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Pedal.png"))); // NOI18N
        jButton1.setText(" ");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/PedalXL.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 130, -1));

        btiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/playXL.png"))); // NOI18N
        btiniciar.setText(" ");
        btiniciar.setContentAreaFilled(false);
        btiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 180, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Reiniciar.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Reinciar2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 130, 80));

        carrito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carreras/carr3.png"))); // NOI18N
        carrito1.setToolTipText("Carro1");
        jPanel1.add(carrito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 50));

        carrito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carreras/carr1.png"))); // NOI18N
        jPanel1.add(carrito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 50));

        carrito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carreras/carr0.png"))); // NOI18N
        jPanel1.add(carrito3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 48));
        jPanel1.add(lbl_barrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 30, 450));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio5/Sin título-23.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio5/paredF.jpg"))); // NOI18N
        fondo2.setText("Fondo2");
        jPanel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btiniciarActionPerformed
        carrito1.setLocation(0,carrito1.getLocation().y);
        carrito2.setLocation(0,carrito2.getLocation().y);
        carrito3.setLocation(0,carrito3.getLocation().y);
         hilo2=new HiloCarro1(carrito2,null);
         hilo3=new HiloCarro1(carrito3,null);
    if(carrito1.getLocation().x>lbl_barrera.getX()){
        JOptionPane.showMessageDialog(null,"Ganador 1");
    }
        try {
            hilo2.start();
            hilo3.start();
        } catch (Exception e) {
        }
        hilo1.resume();
        hilo2.resume();
        hilo3.resume();
    }//GEN-LAST:event_btiniciarActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
     
        try {
        hilo1.start();
        } catch (Exception e) {
        }
        hilo1.resume();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
     hilo1.suspend();
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    carrito1.setLocation(0,carrito1.getLocation().y);
    carrito2.setLocation(0,carrito2.getLocation().y);
    carrito3.setLocation(0,carrito3.getLocation().y);
     hilo2.suspend();
     hilo1.suspend();
     hilo3.suspend();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void miboton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miboton5MousePressed
        hilo1.resume();
    }//GEN-LAST:event_miboton5MousePressed

    private void miboton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miboton5MouseReleased
        hilo1.suspend();
    }//GEN-LAST:event_miboton5MouseReleased

    private void miboton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miboton5ActionPerformed
        Menu m=new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_miboton5ActionPerformed

    private void miboton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_miboton5KeyPressed

    }//GEN-LAST:event_miboton5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carreras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carreras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btiniciar;
    private javax.swing.JLabel carrito1;
    private javax.swing.JLabel carrito2;
    private javax.swing.JLabel carrito3;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_barrera;
    private componentes.Miboton miboton5;
    // End of variables declaration//GEN-END:variables
}
