/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio1;

import Menu.Menu;

/**
 *
 * @author MARCELA GARCIA REVIL
 */
public class Carro extends javax.swing.JFrame {
    HiloCarro Hcarro;
    public Carro() {
        initComponents();
        setLocationRelativeTo(null);
        Hcarro= new HiloCarro(carro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        miboton5 = new componentes.Miboton();
        miboton1 = new componentes.Miboton();
        miboton2 = new componentes.Miboton();
        miboton3 = new componentes.Miboton();
        miboton4 = new componentes.Miboton();
        carro = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miboton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/atras.png"))); // NOI18N
        miboton5.setContentAreaFilled(false);
        miboton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/atras2.png"))); // NOI18N
        miboton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                miboton5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                miboton5MouseReleased(evt);
            }
        });
        miboton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miboton5ActionPerformed(evt);
            }
        });
        miboton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                miboton5KeyPressed(evt);
            }
        });
        jPanel1.add(miboton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 80, 80));

        miboton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Reiniciar.png"))); // NOI18N
        miboton1.setContentAreaFilled(false);
        miboton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Reinciar2.png"))); // NOI18N
        miboton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miboton1ActionPerformed(evt);
            }
        });
        jPanel1.add(miboton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 70, 80));

        miboton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/continuar.png"))); // NOI18N
        miboton2.setContentAreaFilled(false);
        miboton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        miboton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/continuar2.png"))); // NOI18N
        miboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miboton2ActionPerformed(evt);
            }
        });
        jPanel1.add(miboton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 80, 80));

        miboton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Pausa2.png"))); // NOI18N
        miboton3.setContentAreaFilled(false);
        miboton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miboton3ActionPerformed(evt);
            }
        });
        jPanel1.add(miboton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 80, 80));

        miboton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Play.png"))); // NOI18N
        miboton4.setContentAreaFilled(false);
        miboton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miboton4ActionPerformed(evt);
            }
        });
        jPanel1.add(miboton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 80));

        carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hilos1/Imagenes/carroE1.png"))); // NOI18N
        carro.setText(" ");
        jPanel1.add(carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hilos1/Imagenes/Fondo Ciudad_1.jpg"))); // NOI18N
        Fondo.setText(" ");
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miboton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miboton1ActionPerformed
          Hcarro.suspend();
        carro.setLocation(10, 300);
    }//GEN-LAST:event_miboton1ActionPerformed

    private void miboton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miboton2ActionPerformed
   Hcarro.resume();
    }//GEN-LAST:event_miboton2ActionPerformed

    private void miboton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miboton3ActionPerformed
     Hcarro.suspend();
    }//GEN-LAST:event_miboton3ActionPerformed

    private void miboton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miboton4ActionPerformed
             try {
            Hcarro.start();
        } catch (Exception e) {
        }
        Hcarro.resume();
    }//GEN-LAST:event_miboton4ActionPerformed

    private void miboton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miboton5ActionPerformed
    Menu m=new Menu();
    m.setVisible(true);
    dispose();
    }//GEN-LAST:event_miboton5ActionPerformed

    private void miboton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_miboton5KeyPressed
    
    }//GEN-LAST:event_miboton5KeyPressed

    private void miboton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miboton5MousePressed
     Hcarro.resume();
    }//GEN-LAST:event_miboton5MousePressed

    private void miboton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miboton5MouseReleased
     Hcarro.suspend();
    }//GEN-LAST:event_miboton5MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel carro;
    private javax.swing.JPanel jPanel1;
    private componentes.Miboton miboton1;
    private componentes.Miboton miboton2;
    private componentes.Miboton miboton3;
    private componentes.Miboton miboton4;
    private componentes.Miboton miboton5;
    // End of variables declaration//GEN-END:variables
}
