/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Ejercicio1.Carro;
import Ejercicio2.Ejercicio2;
import Ejercicio3.Ejercicio3;
import Ejercicio4.Ejercicio4;
import Ejercicio5.Carreras;

/**
 *
 * @author MARCELA GARCIA REVIL
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mietiqueta1 = new componentes.Mietiqueta();
        mietiqueta2 = new componentes.Mietiqueta();
        mietiqueta3 = new componentes.Mietiqueta();
        mietiqueta4 = new componentes.Mietiqueta();
        mietiqueta5 = new componentes.Mietiqueta();
        mietiqueta6 = new componentes.Mietiqueta();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mietiqueta1.setText("Ejercicio 2");
        mietiqueta1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(mietiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        mietiqueta2.setText("Salir");
        mietiqueta2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(mietiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, -1, -1));

        mietiqueta3.setText("Ejercicio 1");
        mietiqueta3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(mietiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 204, -1, 40));

        mietiqueta4.setText("Ejercicio 3");
        mietiqueta4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(mietiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        mietiqueta5.setText("Ejercicio 4");
        mietiqueta5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(mietiqueta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        mietiqueta6.setText("Ejercicio 5");
        mietiqueta6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPanel1.add(mietiqueta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/log_logout_door_1563_1.png"))); // NOI18N
        jButton2.setText(" ");
        jButton2.setContentAreaFilled(false);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/log_logout_door_15632.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 170, 170));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Boton1.png"))); // NOI18N
        jButton6.setText("Ejercicio 1");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Boton1.1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 134, 136));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/boton2.png"))); // NOI18N
        jButton7.setText("ej2");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/boton2.1.png"))); // NOI18N
        jButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/boton2.1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 128, 135));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/boton3.png"))); // NOI18N
        jButton8.setText("ej3");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Boton31.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 140, 140));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/boton4.png"))); // NOI18N
        jButton9.setText("ej4");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/boton4.1.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 153, 143));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Boton5.png"))); // NOI18N
        jButton10.setText("ej5");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesINT/Boton52.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 134, 143));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio5/paredF.jpg"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Carro car=new Carro();
       car.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      Ejercicio4 ej4= new Ejercicio4();
      ej4.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
     Carreras car= new Carreras();
     car.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Ejercicio2 ej2= new Ejercicio2();
        ej2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     Ejercicio3 e=new Ejercicio3();
     e.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private componentes.Mietiqueta mietiqueta1;
    private componentes.Mietiqueta mietiqueta2;
    private componentes.Mietiqueta mietiqueta3;
    private componentes.Mietiqueta mietiqueta4;
    private componentes.Mietiqueta mietiqueta5;
    private componentes.Mietiqueta mietiqueta6;
    // End of variables declaration//GEN-END:variables
}
